import {
  SquareChartGantt,
  ChartColumn,
  ChartLine,
  Columns3,
  LineSquiggle,
  SquareStop,
  SquareEqual,
  Dice4,
  GalleryHorizontalEnd,
  SquareDashedKanban,
  GalleryThumbnails,
  Container,
  Grid2X2,
  GalleryVerticalEnd,
  TextInitial,
  Scroll,
  Dock
} from "lucide-react";

export const chartMenuIconMap = {
  SquareChartGantt: SquareChartGantt,
  ChartColumn: ChartColumn,
  ChartLine: ChartLine,
  Columns3: Columns3,
  LineSquiggle: LineSquiggle,
  SquareStop: SquareStop,
  SquareEqual: SquareEqual,
  Dice4: Dice4,
  GalleryHorizontalEnd: GalleryHorizontalEnd,
  SquareDashedKanban: SquareDashedKanban,
  GalleryThumbnails: GalleryThumbnails,
  Container: Container,
  Grid2X2: Grid2X2,
  GalleryVerticalEnd: GalleryVerticalEnd,
  TextInitial: TextInitial,
  Scroll: Scroll,
  Dock: Dock,
};
